branches:
  - name: main
  - name: patch-+([0-9])?(.+([0-9])).x
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
tagFormat: "${version}"
