branches:
  - name: main
  - name: patch-+([0-9])?(.{+([0-9]),x}).x
    range: "${name.replace(/^patch-/g, '')}"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
tagFormat: "${version}"
